# Generated by Django 6.0.5 on 2026-06-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_organization_alter_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(max_length=100, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(max_length=100, null=True, verbose_name='Специализация'),
        ),
    ]
