# Generated by Django 6.0.5 on 2026-06-12 06:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LawReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_number', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='casetask',
            name='order',
        ),
        migrations.AddField(
            model_name='casetask',
            name='ideal_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='ai_correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='ai_what_is_correct',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='taskanswer',
            name='ai_what_is_missing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='caseattempt',
            name='total_score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='max_score',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='casetask',
            name='task_type',
            field=models.CharField(choices=[('order', 'Order'), ('test', 'Test'), ('open', 'Open Question')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='score',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='casetask',
            name='law_references',
            field=models.ManyToManyField(blank=True, to='cases.lawreference'),
        ),
    ]
